{
  "module_id": "_sf_error",
  "original_path": "modules\\restored\\_sf_error.py",
  "preserved_path": "preservation_holding_area\\_sf_error_20250621_212755.py",
  "preservation_reason": "audit_preservation",
  "preservation_timestamp": "2025-06-21T18:27:27.190664+00:00",
  "file_size": 16522,
  "checksum": "d67fa119d3ad5bd8bb6fff4bab53062e0bed72c832e7b96e3a8b06715218183b"
}