{
  "module_id": "exceptions",
  "original_path": "modules\\restored\\exceptions.py",
  "preserved_path": "preservation_holding_area\\exceptions_20250621_212808.py",
  "preservation_reason": "audit_preservation",
  "preservation_timestamp": "2025-06-21T18:27:27.190664+00:00",
  "file_size": 49518,
  "checksum": "6e2fe5dda3880cfe4728f8002d068056a06f3ff971c167f6fbf5af5eaf8b916a"
}